### ISSUE TITLE
还是老问题，windows的CMD下全部中文字符集乱码

### ISSUE THREAD

**Issue by yiqian987** [iBreaker/bjguahao#15]
朋友的电脑里没有ide环境，只能用cmd，但是cmd下 乱码严重 utf-8的编码在gbk下废了。。
未修改代码前的屏显
C:\bjguahao-master>bjguahao.py
[0;37m 2017-03-24 15:51:10 [info] DebugLevel璁剧疆涓?2[0m
[0;37m 2017-03-24 15:51:10 [info] 閰嶇疆鍔犺浇瀹屾垚[0m
[0;37m 2017-03-24 15:51:10 [info] 更新时间: 09:30[0m
[0;37m 2017-03-24 15:51:10 [info] 预约周期: 7[0m
[0;37m 2017-03-24 15:51:10 [info] 寮€濮嬬櫥闄?[0m
[0;37m 2017-03-24 15:51:10 [info] 鐧婚檰鎴愬姛[0m
[0;37m 2017-03-24 15:51:11 [info] 鑾峰彇楠岃瘉鐮佹垚鍔?[0m
杈撳叆鐭俊楠岃瘉鐮? 717201
[0;37m 2017-03-24 15:51:36 [info] 褰撳墠鍙蜂綑閲?[0m
+---------------+------+--------+
|    医生姓名   | 擅长 | 号余量 |
+---------------+------+--------+
| 普通专业号5元 |      |   2    |
+---------------+------+--------+
[0;37m 2017-03-24 15:51:36 [info] 选中:普通专业号5元[0m
[0;37m 2017-03-24 15:51:37 [info] 病人ID:231307790[0m
[0;37m 2017-03-24 15:51:37 [info] 鎸傚彿鎴愬姛[0m
修改了字符集后
.encode("GBK", 'ignore')
C:\bjguahao-master>bjguahao.py
[0;37m 2017-03-24 15:47:11 [info] DebugLevel璁剧疆涓?2[0m
[0;37m 2017-03-24 15:47:11 [info] 配置加载完成[0m
[0;37m 2017-03-24 15:47:12 [info] 更新时间: 09:30[0m
[0;37m 2017-03-24 15:47:12 [info] 预约周期: 7[0m
[0;37m 2017-03-24 15:47:12 [info] 开始登陆[0m
[0;37m 2017-03-24 15:47:12 [info] 登陆成功[0m
[0;37m 2017-03-24 15:47:12 [info] 获取验证码成功[0m
输入短信验证码: 922127
[0;37m 2017-03-24 15:47:27 [info] 当前号余量:[0m
+---------------+------+--------+
|    医生姓名   | 擅长 | 号余量 |
+---------------+------+--------+
| 普通专业号5元 |      |   3    |
+---------------+------+--------+
[0;37m 2017-03-24 15:47:27 [info] 选中:普通专业号5元[0m
[0;37m 2017-03-24 15:47:27 [info] 病人ID:231307790[0m
[0;37m 2017-03-24 15:47:27 [info] 挂号成功[0m

**Comment by iBreaker** [comment]
没有在windows下测试   中文显示不正常？

**Comment by yorelog** [comment]
测试cmd内是有乱码的问题 
            在2017年03月24日 16:09，Breaker 写道： 没有在windows下测试   中文显示不正常？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iBreaker/bjguahao","title":"iBreaker/bjguahao","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iBreaker/bjguahao"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iBreaker in #15: 没有在windows下测试   中文显示不正常？"}],"action":{"name":"View Issue","url":"https://github.com/iBreaker/bjguahao/issues/15#issuecomment-288958458"}}}

**Comment by iBreaker** [comment]
你那边解决这个问题了吗？  我回去看看

**Comment by yorelog** [comment]
嗯 编码问题
            在2017年03月24日 16:53，Breaker 写道： 你那边解决这个问题了吗？  我回去看看

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iBreaker/bjguahao","title":"iBreaker/bjguahao","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iBreaker/bjguahao"}},"updates":{"snippets":[{"icon":"PERSON","message":"@iBreaker in #15: 你那边解决这个问题了吗？  我回去看看"}],"action":{"name":"View Issue","url":"https://github.com/iBreaker/bjguahao/issues/15#issuecomment-288966545"}}}

**Comment by yiqian987** [comment]
我这边只是简单的在你编码中有中文的地方进行了.encode("GBK", 'ignore')操作，不过我这方法太low了，应该可以自动检测当前字符集吧

**Comment by yorelog** [comment]
已经在[dev](https://github.com/iBreaker/bjguahao/commit/f248df7feed4a9dc5c8f6f2d398e820e55a834be)提供了Windows下支持
